In [27]:
import numpy as np
data = np.random.randn(2,3)
data

array([[-0.29437906,  0.56542207, -0.38620871],
       [ 0.4122683 ,  0.40846518, -1.24252801]])

In [28]:
data*10

array([[ -2.94379062,   5.65422074,  -3.86208709],
       [  4.12268305,   4.08465177, -12.42528009]])

In [29]:
data+data

array([[-0.58875812,  1.13084415, -0.77241742],
       [ 0.82453661,  0.81693035, -2.48505602]])

In [30]:
data.shape

(2, 3)

In [31]:
data.dtype

dtype('float64')

In [33]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [34]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [38]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [39]:
arr_slice[1]=12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [41]:
arr_slice[:]=64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [60]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [61]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [62]:
arr3d[1,0]

array([7, 8, 9])

In [63]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
arr2d[2]

array([7, 8, 9])

In [65]:
arr2d[2,1]

8

In [66]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
arr2d[:2]        #选取数组的前两行。             区别于列表的切片  行与列，列却满足

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
arr2d[:2,1:]    #先取前两行，再从第二列取到最后

array([[2, 3],
       [5, 6]])

In [70]:
arr2d[1,:2]  #行不含冒号，按照索引规则表示第二行，列表示取到前两列

array([4, 5])

In [71]:
arr2d[:2,2]   #前两行第三列的数组

array([3, 6])

In [72]:
arr2d[:,:1]  #冒号： 表示取整个轴，即 行全取，列只取第一列                         取前不取后！！！！！！！！

array([[1],
       [4],
       [7]])

In [73]:
data = np.random.randn(7,4)  #随机生成7行4列的二维数组
data

array([[ 0.86894029,  0.79539565, -1.54646171,  0.30612584],
       [ 2.09665949,  0.25362973, -0.41470366,  0.70260944],
       [ 0.17640422, -0.64733419, -0.21954555, -1.27935579],
       [ 0.13336012,  1.0571751 , -0.43733181, -0.95222715],
       [ 1.15175243,  0.33619557, -0.44920261,  0.64848747],
       [-0.07602001,  1.33272235,  0.29266882,  0.24539149],
       [-0.47103017, -0.06317628, -0.06380498,  0.70082817]])

In [74]:
data[data<0] = 0
data                 #将data内的所有负值设置为0

array([[0.86894029, 0.79539565, 0.        , 0.30612584],
       [2.09665949, 0.25362973, 0.        , 0.70260944],
       [0.17640422, 0.        , 0.        , 0.        ],
       [0.13336012, 1.0571751 , 0.        , 0.        ],
       [1.15175243, 0.33619557, 0.        , 0.64848747],
       [0.        , 1.33272235, 0.29266882, 0.24539149],
       [0.        , 0.        , 0.        , 0.70082817]])

In [78]:
arr=np.empty((8,4))
for i  in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [79]:
arr[[4,3,0,6]] # 传人用于指定顺序的整数列或ndarray

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [80]:
arr[[-3,-5,-7]] #使用负号索引从末尾开始取行

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [82]:
arr = np.arange(32).reshape(8,4)  #0到31的数组，8行4列
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [83]:
arr[[1,5,7,2],[0,3,1,2]]          #选取（1,0）（5,3）（7,1）（2,2）的值组成一维数组      花式索引总是一维的

array([ 4, 23, 29, 10])

In [84]:
arr[[1,5,7,2]][:,[0,3,1,2]] # 选取第 2 6 8 3行 ，列按[0,3,1,2]进行排序

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [85]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [86]:
arr.T                                 #行列转置

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [87]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [88]:
arr.transpose((1,0,2)) #???????????????

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [89]:
arr = np.arange(10) 
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
np.sqrt(arr)  #平方根

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [91]:
np.exp(arr)  #e的幂次方

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [92]:
x = np.random.randn(8) 
x

array([ 0.83653232, -0.36991148, -0.17808332,  1.3485722 ,  0.793194  ,
        1.0534475 , -1.23685785, -2.67514461])

In [93]:
y = np.random.randn(8)
y

array([ 0.40564018, -0.15501132, -0.46913865,  0.23061504,  0.19098801,
       -0.77710732,  2.00506865,  1.23442874])

In [94]:
np.maximum(x,y)                                               #计算了x和y中元素级别较大的元素

array([ 0.83653232, -0.15501132, -0.17808332,  1.3485722 ,  0.793194  ,
        1.0534475 ,  2.00506865,  1.23442874])

In [95]:
arr = np.random.randn(7) * 5
arr

array([ 5.91414672, -0.85091526, -0.90063184, 12.50968705, 10.20673501,
        5.58632194, -4.11866191])

In [96]:
remainder, whole_part = np.modf(arr)          #取其浮点数
remainder

array([ 0.91414672, -0.85091526, -0.90063184,  0.50968705,  0.20673501,
        0.58632194, -0.11866191])

In [97]:
whole_part

array([ 5., -0., -0., 12., 10.,  5., -4.])

In [98]:
arr

array([ 5.91414672, -0.85091526, -0.90063184, 12.50968705, 10.20673501,
        5.58632194, -4.11866191])

In [99]:
np.sqrt(arr)

D:\Anaconda111\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([2.43190187,        nan,        nan, 3.5369036 , 3.19479812,
       2.36354013,        nan])

In [102]:
points = np.arange(-5,5,0.01) 
xs,ys = np.meshgrid(points,points)
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [103]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [105]:
z = np.sqrt(xs**2 + ys**2)
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [108]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = np.where(cond,xarr,yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [109]:
arr = np.random.randn(4,4)
arr

array([[-2.6444286 ,  0.68846244,  1.3779205 , -1.31981709],
       [ 0.85476607, -1.05486521,  1.38289732, -0.82592014],
       [ 0.30268405,  0.74369202, -0.60027877, -0.93915691],
       [ 1.53301936,  0.94200858,  1.55013125, -2.30248117]])

In [110]:
arr>0

array([[False,  True,  True, False],
       [ True, False,  True, False],
       [ True,  True, False, False],
       [ True,  True,  True, False]])

In [111]:
np.where(arr>0,2,-2)

array([[-2,  2,  2, -2],
       [ 2, -2,  2, -2],
       [ 2,  2, -2, -2],
       [ 2,  2,  2, -2]])

In [112]:
np.where(arr>0,2,arr)

array([[-2.6444286 ,  2.        ,  2.        , -1.31981709],
       [ 2.        , -1.05486521,  2.        , -0.82592014],
       [ 2.        ,  2.        , -0.60027877, -0.93915691],
       [ 2.        ,  2.        ,  2.        , -2.30248117]])

In [113]:
arr = np.random.randn(5,4)
arr

array([[-0.18294254,  0.11573136, -1.34972937,  1.55876823],
       [ 0.69080986,  0.48299547,  0.2393127 ,  0.64300157],
       [-0.29369057, -1.00785552,  0.46836443, -1.09918026],
       [ 0.39964888, -0.03584178, -0.27613072, -2.26089121],
       [-1.42185221, -1.46762769, -1.50732709, -0.29546016]])

In [114]:
arr.mean()

-0.3299948321787648

In [115]:
arr.sum()

-6.599896643575296

In [119]:
arr.mean(axis=1)        #每一行的平均值

array([ 0.03545692,  0.5140299 , -0.48309048, -0.54330371, -1.17306679])

In [117]:
arr.sum(axis=0)       #计算每一列的和

array([-0.80802658, -1.91259818, -2.42551006, -1.45376183])

In [123]:
arr = np.random.randn(100)
arr

array([-0.82427401,  1.40766332,  0.19510826,  1.30181928,  0.33427886,
        0.15750194,  2.86468225,  1.20601143,  0.49555407, -0.99380628,
       -0.63771825, -1.65096335,  0.17570976, -1.83383405,  0.64408681,
        0.63674261,  2.08852868,  1.033756  , -0.89858458,  0.92841485,
        0.19212803, -0.60977974, -1.86996525, -1.70700609,  1.0964929 ,
        1.75389819,  1.18729641,  0.01700152, -0.67937537, -1.07343085,
       -0.31408849, -0.57652494,  0.08943591, -0.37687776,  0.25349475,
       -0.78230439, -0.63291867,  0.4352368 , -1.51729771, -0.34242509,
        1.83745707,  0.77276246, -1.06084199,  1.15669806,  0.85118167,
       -0.06824131, -0.80010189, -0.72782597, -0.53328672, -0.90336139,
        0.79089544, -0.92603237,  0.82985925, -0.74170551, -0.64016102,
        0.67023652,  0.35871902,  1.09143368, -1.67768944,  0.35659963,
       -0.39149141,  0.57808667, -0.14088948, -1.01221485,  0.65795048,
        0.97815086,  0.60251649, -0.7360337 ,  1.33219449,  0.18

In [124]:
(arr>0).sum()

53

In [140]:
arr = np.random.randn(5,4)
arr

array([[-0.60953906,  0.87014741,  0.22448223, -0.73996808],
       [-0.0845471 ,  1.17207138,  0.97861441, -0.02287254],
       [-0.86006027,  0.46313513,  2.13346785,  0.26988258],
       [-0.0301096 ,  0.08996033,  1.00682519, -1.42636858],
       [-1.03566728, -1.65858678,  1.92262653,  0.20407242]])

In [141]:
arr.sort(1)
arr

array([[-0.73996808, -0.60953906,  0.22448223,  0.87014741],
       [-0.0845471 , -0.02287254,  0.97861441,  1.17207138],
       [-0.86006027,  0.26988258,  0.46313513,  2.13346785],
       [-1.42636858, -0.0301096 ,  0.08996033,  1.00682519],
       [-1.65858678, -1.03566728,  0.20407242,  1.92262653]])