# pandas 入门

## 1.pandas数据结构

In [2]:
import pandas as pd 
import numpy as np

In [3]:
from pandas import Series , DataFrame           #注意大写格式

  1. Seris              类似于一维数组的对象

In [5]:
obj = pd.Series([4,7,-5,3])
obj                                      #  列为值，在右边；在没有指定索引的情况下，
                                          #   在左边自动生成一个0到N-1的整数型索引

0    4
1    7
2   -5
3    3
dtype: int64

In [6]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [7]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
obj2 = pd.Series([4,7,-5,3],index=['d','b','c','a'])
obj2                                  #通过  index = [],来规定其索引

d    4
b    7
c   -5
a    3
dtype: int64

In [10]:
obj2.index          # 注意数据格式   object！！！！

Index(['d', 'b', 'c', 'a'], dtype='object')

通过索引的方式获取Series中单个值或一组值（即索引列表）

In [11]:
obj2['a']

3

In [13]:
obj2['d']

4

In [14]:
obj2[['c','a','d']]     #列表中的列表

c   -5
a    3
d    4
dtype: int64

In [16]:
obj2[obj2>0]                       # 使用Numpy函数的运算会保留其对应的索引

d    4
b    7
a    3
dtype: int64

In [17]:
obj2*2

d     8
b    14
c   -10
a     6
dtype: int64

In [21]:
np.exp(obj2)            # np.exp()  e的N次方

d      54.598150
b    1096.633158
c       0.006738
a      20.085537
dtype: float64

通过   in 来判断 索引是否在Series中 (类似python中的dict)

In [22]:
'b' in obj2

True

In [23]:
'e' in obj2

False

通过python中的字典来创建Series：

In [25]:
sdata = {'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [29]:
states = ['California','Ohio','Oregon','Texas']
obj4 = pd.Series(sdata,index=states)
obj4                  #如果只传入一个字典，则结果Series中的索引就是原字典中的键，
                      # 可以传入排好序的字典的键来改变顺序   
                # 'California'对应的sdata值找不到，结果返回 NaN（非数字 not a number）
                 # 'Utah'不在states中，它被从结果中除去

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

pandas 的 isnull(缺失，无效的) 和 notnull（不缺失，有效的） 函数可用于检测是否缺失数据：

In [30]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [31]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [34]:
obj4.isnull()              #Series 也有 isnull() 和notnull() 这样的实例方法

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [33]:
obj4.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [35]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [36]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [38]:
obj3 + obj4                 #根据运算的索引标签自动对齐数据

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

Series 本身和索引的name属性         obj.name = ''    obj.index.name = ''

In [39]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

Series 的索引可以通过赋值的方式就地修改

In [40]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [41]:
obj.index = ['Bob','steve','Jeff','Ryan']
obj

Bob      4
steve    7
Jeff    -5
Ryan     3
dtype: int64

 ## 2.DataFrame

   DataFrame是一个表格型的数据结构，它含有一组有序的列，每列可以是不同的值类型（数值、字符串、布尔值等）。DataFrame既有行索引也有列索引，它可以看做由Series组成的字典（共同拥有一个索引）（多个Series经过横向连接，共同拥有行索引）

In [47]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
        'year':[2000,2001,2002,2001,2002,2003],
        'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)
frame                       #直接传入一个由等长！列表或Numpy数组组成的字典（！字典！）    规定的是列索引！！！！行索引默认range（N）

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [49]:
frame.head()        # 表示只看前五行， 可以在head()函数中传入参数，表示你想看多少行

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

如果指定了列序列，则DataFrame的列就会按照指定顺序进行排列：

In [51]:
pd.DataFrame(data,columns=['year','state','pop'])       #按照指定顺序排列 ，  columns：列索引


year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [54]:
frame2 = pd.DataFrame(data,columns=['year','state','pop','debt'],index=['one','two','three','four','five','six'])  
frame2                      #如果传入的列在数据中找不到，就会在结果中产生缺失值   用 columns=[]规定列索引, index=[] 规定行索引

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [55]:
frame2.columns         #查看列索引

Index(['year', 'state', 'pop', 'debt'], dtype='object')

通过类似字典标记的方法或属性的方法，可以将DataFrame的列获取为一个Series：

In [56]:
frame2['state']        #建议使用 DataFrame[colums] 这个方法

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [58]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

行也可以通过位置或名称的方式进行获取，比如用loc属性：

In [59]:
frame2.loc['three']       # loc（）行索引 ，iloc（）行号

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

 列可以通过赋值的方式进行修改，如：

In [60]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [63]:
frame2['debt'] = np.arange(6.)          #注意一整列的格式：array 用np.    浮点数 6.   赋值给列的长度必须跟DataFrame的长度相匹配
frame2 

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [65]:
val = pd.Series([-1.2,-1.5,-1.7],index = ['two','four','five'])
frame2['debt'] = val
frame2                         #如果赋值的是一个Series，会通过指定的index 赋值，所有的空位将填补缺失值NaN 

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

del  删除列  #drop属性

In [75]:
frame2['eastern'] = frame2.state =='Ohio'
frame2      #添加一个新的布尔值的列 ， state是否为'Ohio'

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [76]:
del  frame2['eastern']
frame2.columns
frame2          #del 会直接修改源数据 

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

如果嵌套字典传给DataFrame ，pandas就会被解释为： 外层字典的键作为列！，内层键作为行索引

In [77]:
pop = {'Neveda':{2001:2.4,2002:2.9},'Ohio':{2000:1.5,2001:1.7,2002:3.6}}
frame3 = pd.DataFrame(pop)
frame3                 #内层键被合并

Neveda  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [79]:
frame3.T      #转置

2000  2001  2002
Neveda   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

内层字典的键会被合并、排序以形成最终的索引。如果明确指定了索引，则不会合并：

In [80]:
pd.DataFrame(pop,index=[2001,2002,2003])

Neveda  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

由 Series（一维）组成的字典也差不多也是一样的用法：

In [82]:
pdata = {'Ohio':frame3['Ohio'][:-1],
         'Nevada':frame3['Neveda'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

DataFrame 的index和columns的name属性   即index.name 和 columns.name

In [83]:
frame3.index.name='year'
frame3.columns.name='state'
frame3

state  Neveda  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

跟Series一样，values属性也会以二维ndarray的形式返回DataFrame中的数据：

In [84]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [85]:
frame2.values          #dtype = object ，DataFrame各列的数据类型不同时，会选用兼容所有的数据类型

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## 索引对象 

In [87]:
obj = pd.Series(range(3),index=['a','b','c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [88]:
index[1:]

Index(['b', 'c'], dtype='object')

In [93]:
index[1] = 'd'   # Index对象是不可变的，不可对其进行修改

TypeError: Index does not support mutable operations

不可变可以使Index对象在多个数据结构之间安全共享：

In [94]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [95]:
obj2 = pd.Series([1.5,-2.5,0],index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [96]:
obj2.index is labels

True

Index功能类似一个固定大小的集合

In [97]:
frame3

state  Neveda  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [98]:
frame3.columns

Index(['Neveda', 'Ohio'], dtype='object', name='state')

In [99]:
'Ohio' in frame3.columns

True

In [100]:
2003 in frame3.columns

False

与python不同，pandas的Index可以包含重复的标签：

In [102]:
dup_labels = pd.Index(['foo','foo','bar','bar'])
dup_labels                  # index 与Index的区别  index = []   Index[]  注意= 赋值符号！！

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## 2.基本功能 

重新索引 reindex

In [104]:
obj = pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [105]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2                                    #用该Series的reindex将会根据新索引进行重排。
                                        #如果某个索引不存在，就引入缺失值。

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

对于时间序列这样的有序序列，重新索引时可能需要做一些插值处理。
method选项即可达到此目的，例如，使用ffill可以实现前项值填充。

In [107]:
obj3 = pd.Series(['blue','purple','yellow'],index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [108]:
obj3.reindex(range(6),method='ffill')   #向前填充

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

借助DataFrame，reindex可以修改（行）索引和列

In [110]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),index = ['a','c','d'],columns=['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [111]:
frame2 = frame.reindex(['a','b','c','d'])
frame2                            #只传递一个序列时，会重新索引结果的行，即改变行索引！

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [112]:
states = ['Texas','Utah','California']
frame.reindex(columns=states)    # 使用columns参数可以重新索引结果的列，即改变列索引！

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

丢弃指定轴上的项     drop方法  返回的是一个在指定轴上删除了指定对象的新对象

In [124]:
obj = pd.Series(np.arange(5.),index = ['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [114]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [115]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

对于DataFrame，可以删除任意轴上的值        不额外写默认删除行索引，加了axis=1或者axis='columns' 删除列索引

In [117]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','NY'],columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
NY         12   13     14    15

In [119]:
data.drop(['Colorado','Ohio'])        #用标签序列调用drop会从行标签（axis=0）删除值

one  two  three  four
Utah    8    9     10    11
NY     12   13     14    15

In [120]:
data.drop('two',axis=1)  #通过传递axis=1或axis=‘columns’删除列的值

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
NY         12     14    15

In [121]:
data.drop(['two','four'],axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
NY         12     14

就地修改对象，不返回新的对象   inplace=True （慎用）

In [125]:
obj.drop('c',inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

索引、选取和过滤

In [126]:
obj = pd.Series(np.arange(4.),index=['a','b','c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [127]:
obj['b']

1.0

In [128]:
obj[1]

1.0

In [129]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [130]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [132]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [134]:
obj[obj<2]      #选取Series数组值中小于2的数组值

a    0.0
b    1.0
dtype: float64

利用标签的切片运算与普通的python切片运算不同，其末端是包含的  标签！！！！！！

In [135]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [138]:
obj[1:3]

b    1.0
c    2.0
dtype: float64

In [142]:
obj['b':'c'] = 5
obj                 #用切片可以对Series的相应部分进行设置

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

用一个值或序列对DataFrame进行索引其实就是获取一个或多个列：

In [143]:
data =  pd.DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','NY'],columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
NY         12   13     14    15

In [148]:
data['two']

Ohio         1
Colorado     5
Utah         9
NY          13
Name: two, dtype: int32

In [146]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
NY           14   12

In [151]:
data[:2] #选取行

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [150]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
NY         12   13     14    15

通过布尔型DataFrame进行索引：

In [152]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
NY        False  False  False  False

In [153]:
data[data<5]=0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
NY         12   13     14    15

对DataFrame的行的标签索引， 使用轴标签（loc）或整数索引（iloc），可以选择（行和列）(行∩列)的子集

In [163]:
data.loc['Colorado',['two','three']]       #df.loc[val1,val2]通过标签，同时选取行和列  df.loc[:,val2]行索引要写，全取！ 表示取单列或列子集  

two      5
three    6
Name: Colorado, dtype: int32

In [156]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [157]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [158]:
data.loc[:'Utah','two']      #切片  标签切片 包含末标签

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [162]:
data.iloc[:,:3][data['three']>5]                 #data.three>5 等价于 data['three']>5  表示取 数值大于5的行

one  two  three
Colorado    0    5      6
Utah        8    9     10
NY         12   13     14

In [165]:
data.at['NY','one']             #at[]  iat[]  通过行和列的标签   行和列的位置（整数索引） 获取单一的标量

12

整数索引           习惯使用loc（标签）和iloc（整数索引）   切片包含末尾的标签索引

算数运算和数据对齐 

In [168]:
s1 = pd.Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])
s1


a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [169]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [170]:
s1+s2       #pandas可以对不同索引的对象进行算数运算。在将对象相加时，如果存在不同的索引对，则结果的索引就是该索引对的并集，及合并起来
            #自动的数据对齐操作在不重叠的索引出引入了NaN值。缺失值会在算术运算过程中传播
            #同样适用在DataFrame中 ，发生在行和列上

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [179]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'),index = ['Ohio','Texas','COlorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)),index = ['Utah','Ohio','Texas','Oregon'],columns=list('bde'),)
df1                  #list(str) 列表生成器

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
COlorado  6.0  7.0  8.0

In [180]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [182]:
df1-df2            # 没有共同的索引或行标签，结果均为空值 即 NaN

b   c    d   e
COlorado  NaN NaN  NaN NaN
Ohio     -3.0 NaN -2.0 NaN
Oregon    NaN NaN  NaN NaN
Texas    -3.0 NaN -2.0 NaN
Utah      NaN NaN  NaN NaN

In [183]:
df1 = pd.DataFrame({'A':[3,4]})
df1

A
0  3
1  4

在算数方法中填充值  某个对象找不到时，填充一个特殊值  将NaN变成其他   

In [184]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),columns = list('abcd'))
df2 = pd. DataFrame(np.arange(20.).reshape((4,5)),columns = list('abcde'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [185]:
df2.loc[1,'b'] = np.nan
df2         #用loc[] 标签，将标量改为  nan（np.nan）

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [186]:
df1 + df2      #相加，没有重叠!!!!的位置就会产生NaN

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [190]:
df1.add(df2,fill_value=0)          #add()方法，第一个参数传入需要相加的对象，第二个参数fill_value=0 表示正常进行相加，将原来的值传入

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [189]:
df1.reindex(columns=df2.columns,fill_value=0)      #在对Series或DataFrame重新定义索引时，也可以指定一个填充值

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

DataFrame和Series之间的运算

In [192]:
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [193]:
arr[0]  #取array的第一行

array([0., 1., 2., 3.])

In [195]:
arr - arr[0]  #用arr-arr[0]时，每一行每一行！！！都会执行这个操作，称之为广播

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [196]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),index = ['Utah','Ohio','Texas','Oregon'],columns = list('bde'))
series = frame.iloc[0]
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [197]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [198]:
frame - series   #默认情况下，会沿着列一直向下广播

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [199]:
series2 = pd.Series(range(3),index = ['b','e','f'])
series2

b    0
e    1
f    2
dtype: int64

In [201]:
frame + series2   #如果某个索引在DataFrame的列和Series的索引中找不到，则参与运算的两个对象就会被重新索引以形成并集

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

匹配行且在列上传播，则必须使用算数运算方法 ：

In [203]:
series3 = frame['d']
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [204]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [205]:
frame - series  #匹配列

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [208]:
frame.sub(series3,axis=0)        #匹配行索引  传入 axis=0 或axis = ‘index’

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

函数应用和映射

Numy的ufuns（元素级数组方法）也可用于操作pandas对象：

将函数应用到由各列或行所形成的一堆数组上，DadaFrame的apply方法可实现

In [209]:
frame = pd.DataFrame(np.random.randn(4,3),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])
frame

b         d         e
Utah    1.589586 -1.742272  0.486600
Ohio   -1.505559  0.353046 -1.121163
Texas  -0.370941  0.915545 -0.157800
Oregon -0.717161 -0.995148  1.435414

In [211]:
f = lambda x : x.max()- x.min()
frame.apply(f)     #这里的函数f，计算了一个Series的最大值和最小值的差，在frame的每列都执行了一次。
                   #结果是一个Series，使用frame的列作为索引

b    3.095145
d    2.657817
e    2.556578
dtype: float64

In [212]:
frame.apply(f,axis='columns')   # axis = ‘columns’ 每行执行，列与列比大小

Utah      3.331858
Ohio      1.858605
Texas     1.286486
Oregon    2.430562
dtype: float64

传递到apply的函数不是必须返回一个标量，还可以返回由多个值组成的Series：

In [213]:
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])
frame.apply(f)

b         d         e
min -1.505559 -1.742272 -1.121163
max  1.589586  0.915545  1.435414

排序和排名 sort_index()   默认行索引    sort_index（axis=1）为列索引

In [214]:
obj = pd. Series(range(4),index=['d','a','b','c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [215]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

对于DataFrame，可以根据任意一个轴上的索引进行排序：

In [218]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),index = ['three','one'],columns = ['d','a','b','c'])
frame                     

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [220]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [222]:
frame.sort_index(axis=1)   #按列索引排序

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [223]:
frame.sort_index(axis=1,ascending=False)   #数据默认是按升序（ascending）排序的，也可以降序

d  c  b  a
three  0  3  2  1
one    4  7  6  5

若要按值对Series进行排序，可使用其sort_values方法：

In [224]:
obj= pd.Series([4,7,-3,2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [225]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [226]:
obj = pd.Series([4,np.nan,7,np.nan,-3,2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [228]:
obj.sort_values()  #在排序时，任何缺失值默认都会被放在Series的末尾

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

当排序一个DataFrame时，你可能希望根据一个或多个列中的值进行排序。将一个或多个列的名字传递给sort_values的by选项可达成目的：

In [230]:
frame = pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [231]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [233]:
frame.sort_values(by=['b','a'])   #根据多个列进行排序，传入名称的列表即可
                                  #优先以by的第一个传入的为主！！！！！

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

rank（）方法！    这是一个排名函数，目的就是按照某种规则（从大到小，从小到大）给原序列的值进行排名。所返回的结果也是一个序列，它展示原序列中每一个值在序列中的名次

In [6]:
ser = pd.Series([0,1,2,3,4,5])
ser

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

In [8]:
ser.rank()         #0序列的值0在所有的值中排名第一位 用1.0表示

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
dtype: float64

In [9]:
obj = pd.Series([7,-5,7,4,2,0,4])
obj                                #出现重复值时，默认取他们排名次序值得平均值

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [5]:
obj.rank() 

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [12]:
obj.rank(method='first')    #rank='fiest'方法，根据值在原数据中出现的顺序排序 ， 标签0、2的值相同，但标签0先出现（在标签2的前面），所以排名6

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [15]:
obj.rank(ascending=False,method='max')  #ascending=Falise 降序！ method='max'  重复值取最大的排名序列

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

 rank（）在DataFrame中

In [17]:
frame=pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],'c':[-2,5,8,-2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [19]:
frame.rank(axis='columns')   #在列上，列与列计算排名

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

带有重复标签的索引

In [21]:
obj=pd.Series(range(5),index=['a','a','b','b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [22]:
obj.index.is_unique   #通过索引的is_unique属性告诉你索引的值是否是唯一的

False

对于带有重复值的索引的Series，如果某个索引对应多个值，则返回一个Series：对应单个值，则返回一个标量值

In [23]:
obj['a']

a    0
a    1
dtype: int64

In [24]:
obj['c']

4

DataFrame也是如此

In [25]:
df = pd.DataFrame(np.random.randn(4,3),index=['a','a','b','b'])
df

0         1         2
a  1.049455  0.120939 -0.570450
a  0.581289 -0.178997 -0.765474
b  0.550736 -0.186092  0.000326
b  0.583074  0.520007  0.474713

In [29]:
df.loc['a']         #df[] 默认取列索引，df.loc[]根据行标签选取

0         1         2
a  1.049455  0.120939 -0.570450
a  0.581289 -0.178997 -0.765474

## 3.汇总和计算描述统计

In [30]:
df = pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],index = ['a','b','c','d'],columns = ['one','two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [32]:
df.sum()    #列求和

one    9.25
two   -5.80
dtype: float64

In [34]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

NA值会自动被排除，除非整个切片（这里指的是行或列）都是NA。通过skipna选项可禁用次功能（默认True）

In [35]:
df.mean(axis='columns',skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

有些方法（如idxmin和idxmax）返回的是间接统计（达到最小值和最大值的索引）

In [36]:
df.idxmax()

one    b
two    d
dtype: object

In [38]:
df.cumsum()  #累积和，nan返回nan

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [39]:
df.describe()  #describe() 一次性产生多个汇总描述

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [40]:
obj = pd.DataFrame(['a','a','b','c']*4)
obj

0
0   a
1   a
2   b
3   c
4   a
5   a
6   b
7   c
8   a
9   a
10  b
11  c
12  a
13  a
14  b
15  c

In [41]:
obj.describe()      #非数值型

0
count   16
unique   3
top      a
freq     8

相关系数与协方差

唯一值、值计数一起成员资格

In [42]:
obj = pd.Series(['c','a','d','a','a','b','b','c','c'])
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [45]:
uniques = obj.unique()
uniques               #得到Series中的唯一值数组  重复取其一  可以通过sort（）进行排序

array(['c', 'a', 'd', 'b'], dtype=object)

In [46]:
obj.value_counts()      #value_counts 计算一个Series中各值出现的频率，默认降序排序，sort = Falise

c    3
a    3
b    2
d    1
dtype: int64

In [47]:
pd.value_counts(obj.values,sort=False)  #value_counts还是一个pandas方法，可以用于任何数组或序列

a    3
c    3
d    1
b    2
dtype: int64

In [48]:
  obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [49]:
mask = obj.isin(['b','c'])
mask      # isin 计算一个表示‘Series各值是否包含于传入的值序列中’的布尔值数组

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [50]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [51]:
to_match = pd.Series(['c','a','b','b','c','a'])
unique_vals = pd.Series(['c','b','a'])
to_match

0    c
1    a
2    b
3    b
4    c
5    a
dtype: object

In [52]:
unique_vals

0    c
1    b
2    a
dtype: object

In [53]:
pd.Index(unique_vals).get_indexer(to_match)           #pd.Index(a).get_indexer(b)  数组b的值对应a中的值的索引

array([0, 2, 1, 1, 0, 2], dtype=int64)

有时，希望得到DataFrame中多个相关列的一张柱状图：

In [55]:
data = pd.DataFrame({'Qu1':[1,3,4,3,4],'Qu2':[2,3,1,2,3],'Qu3':[1,5,2,4,4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [60]:
result = data.apply(pd.value_counts).fillna(0)       #将pandas.value_counts传给DataFrame的apply函数   fillna（0）空值NaN用0填充
result                        #行标签是所有列中的唯一值（行标签是数组或列中的唯一值），后面的频率值是每个列中这些值得相应计数
                             #行标签1 在Qu1列中出现1次，行标签2在Qu1中出现0次，行标签3在Qu1列中出现2次

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0