# 第一章 预备知识
## 一、Python基础
## 1. 列表推导式与条件赋值

#### 在生成一个数字序列时，在Python中可以如下写出：

In [1]:
L = [ ]
def my_func(x):
    return 2*x
for i in range(5):
    L.append(my_func(i))
L    

[0, 2, 4, 6, 8]

#### 实际上可以使用列表推导式进行写法上的简化：[* for i in * ]。其中，第一个*为映射函数，其输入为后面 i 指代的内容，其输入为后面 i 指代的内容，第二个 * 表示迭代的对象。

In [2]:
[my_func(i) for i in range(5)]

[0, 2, 4, 6, 8]

#### 列表表达式还支持多层嵌套，如 下面的例子中第一个for为外层循环，第二个为内层循环：

In [4]:
[m + '_' + n for m in ['a','b'] for n in ['c','d']]

['a_c', 'a_d', 'b_c', 'b_d']

#### 除了列表推导式，另一个实用的语法糖是带有 if 选择的条件赋值，其形式为 value = a if condition else b ：

In [6]:
value = 'cat' if 2 > 1 else 'dog'
value

'cat'

In [8]:
a,b = 'cat','dog'
condition = 2 > 1 #此时为 True
if condition:
    value = a
else :
    value = b
value

'cat'

In [9]:
L = [1,2,3,4,5,6,7]
[i if i<=5 else 5 for i in L]

[1, 2, 3, 4, 5, 5, 5]

## 2. 匿名函数与map方法
#### 有一些函数的定义具有清晰简单的映射关系，例如上面的 my_func函数，这时候可以用匿名函数的方法简洁地表示：

In [10]:
my_func = lambda x: 2*x
my_func(3)

6

In [11]:
multi_para_func = lambda a,b: a + b
multi_para_func(1,2)

3

In [13]:
[(lambda x:2*x) (i) for i in range(5)]

[0, 2, 4, 6, 8]

In [15]:
list(map(lambda x: 2*x , range(5)))  # map(lambda x: y , x(x的取值范围)) 返回的是map对象，记得 list来转换等。

[0, 2, 4, 6, 8]

#### 对于多个输入值的函数映射，可以通过追加迭代对象实现：

In [17]:
list(map(lambda x,y:str(x) + '_' + y,range(5),list('abcde')))

['0_a', '1_b', '2_c', '3_d', '4_e']

## 3.zip对象与enumerate方法
#### zip函数能够把多个迭代对象打包成一个由元组构成的可迭代对象，它返回了一个zip对象，通过tuple，list可以得到相应的打包结果：

In [18]:
L1,L2,L3 = list('abc'),list('def'),list('hij')
list(zip(L1,L2,L3))

[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')]

In [19]:
tuple(zip(L1,L2,L3))

(('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j'))

In [20]:
for i,j,k in zip(L1,L2,L3):
    print(i,j,k)

a d h
b e i
c f j


In [21]:
L = list('abcd')
for index,value in enumerate(L):
    print(index,value)

0 a
1 b
2 c
3 d


#### 当需要对两个列表建立字典映射时，可以利用zip对象，再dict：

In [22]:
dict(zip(L1,L2))

{'a': 'd', 'b': 'e', 'c': 'f'}

#### 既然有压缩函数，那么Python也提供了*操作符和 zip联合来进行解压操作：

In [23]:
zipped = list(zip(L1,L2,L3))
zipped

[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')]

In [24]:
list(zip(*zipped)) #三个元组分别对应原来的列表

[('a', 'b', 'c'), ('d', 'e', 'f'), ('h', 'i', 'j')]

## 二、Numpy基础
## 1.np数组的构造

In [25]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

#### 【a】等差序列：np.linspace,np.arange

In [26]:
np.linspace(1,5,11)  # 起始、终止（包含）、样本个数  （5-1）/ （11-1） = 0.4 

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [ ]:
np.arange(1,5,2) # 起始、终止（不包含）、样本个数 （5-1）/2 = 2 

#### 【b】特殊矩阵： zeros,eye,full

In [27]:
np.zeros((2,3)) #生成 2行3列 都是0的矩阵 ，传入元组表示各维度大小

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.eye(3) # 3*3的单位矩阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.eye(3,k=1) # 偏移量对角线1个单位的伪单位矩阵

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [31]:
np.eye(3,k=-1) # 偏移量对角线1个单位的伪单位矩阵    k值正负值分别表示不同的方向，正表示右方向，负则左

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [32]:
np.full((2,3),10)  #  生成一个2*3皆为10的矩阵，元组传入大小，10表示填充数

array([[10, 10, 10],
       [10, 10, 10]])

In [33]:
np.full((2,3),[1,2,3]) # 通过传入列表填充每列的值

array([[1, 2, 3],
       [1, 2, 3]])

#### 【c】随机矩阵：np.random

In [37]:
np.random.rand(3) # 生成服从0-1均匀分布的三个随机数

array([0.71042125, 0.01609557, 0.67463414])

In [38]:
np.random.rand(3,3) # 传入的不是元组，而是维度的大小分开输入

array([[0.22669829, 0.28418596, 0.9179521 ],
       [0.87896814, 0.02480471, 0.37646053],
       [0.79533076, 0.11518171, 0.58820731]])

In [39]:
a,b = 5,15
(b-a)*np.random.rand(3)+a

array([12.42973845, 13.8746932 , 11.9101242 ])

In [40]:
np.random.randn(3)

array([ 0.28916015, -1.62123707, -1.17125866])

In [41]:
np.random.randn(3,3)

array([[-0.79812319,  2.4143102 , -0.48014192],
       [-0.48155954,  1.72385651,  1.54465597],
       [-1.52214443,  0.13587171, -0.5174244 ]])

In [42]:
np.random.randint(5,15,(2,2))

array([[14, 11],
       [11, 13]])

In [44]:
my_list = ['a','b','c','d']
np.random.choice(my_list,2,replace = False,p=[0.1,0.1,0.7,0.1])  # replace = True , True 表示可以放回即重复抽样，False不可以

array(['c', 'a'], dtype='<U1')

In [45]:
np.random.choice(my_list,(3,3))

array([['d', 'c', 'd'],
       ['a', 'b', 'b'],
       ['b', 'c', 'd']], dtype='<U1')

In [46]:
np.random.permutation(my_list)

array(['a', 'd', 'b', 'c'], dtype='<U1')

In [47]:
np.random.seed(0)
np.random.rand()

0.5488135039273248

In [48]:
np.random.seed(0)
np.random.rand()

0.5488135039273248

## 2. np数组的变形与合并

【a】转置：T

In [49]:
np.zeros((2,3)).T  # 2*3 变成 3*2

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

【b】合并操作：r_，c_

In [50]:
np.r_[np.zeros((2,3)),np.zeros((2,3))]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
np.c_[np.zeros((2,3)),np.zeros((2,3))]

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [58]:
np.r_[np.zeros((2,3)),np.zeros((3,4))] #需要维度大小相同？ 一维数组除外

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

In [53]:
try:
    np.r_[np.array([0,0]),np.zeros((2,1))]
except Exception as e:
    Err_msg = e
Err_msg    

ValueError('all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)')

In [54]:
np.c_[np.array([0,0]),np.zeros((2,1))]

array([[0., 0.],
       [0., 0.]])

In [55]:
 np.r_[np.array([0,0]),np.zeros(2)]

array([0., 0., 0., 0.])

In [56]:
np.c_[np.array([0,0]),np.zeros((2,3))]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### 【c】维度变换：reshape

In [57]:
target = np.arange(8).reshape(2,4)
target

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [60]:
target.reshape((4,2),order = 'C') #按照行读取与填充

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [61]:
target.reshape((4,2),order = 'F') # 按照列读取和填充

array([[0, 2],
       [4, 6],
       [1, 3],
       [5, 7]])

#### 特别地，由于被调用数组的大小是确定的，reshape允许有一个维度存在空缺，此时只需填充-1即可：

In [62]:
target.reshape(4,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [65]:
target = np.ones((3,1))
target

array([[1.],
       [1.],
       [1.]])

In [66]:
target.reshape(-1)

array([1., 1., 1.])

## 3.np数组的切片与索引

In [67]:
target = np.arange(9).reshape(3,3)
target

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
target[:-1,[0,2]] #表示取 前2行的第1、3列

array([[0, 2],
       [3, 5]])

In [72]:
target[:3,[0,2]]

array([[0, 2],
       [3, 5],
       [6, 8]])

In [73]:
target[[0,2],[0,2]]

array([0, 8])

In [77]:
target[0::2,0::2]   # 切片正常，索引需要加上  []

array([[0, 2],
       [6, 8]])

此外，还可以利用 np.ix_在对应的维度上使用布尔索引，单此时不能使用slice切片：

In [78]:
target[np.ix_([True,False,True],[True,False,True])]

array([[0, 2],
       [6, 8]])

In [79]:
target[np.ix_([1,2],[True,False,True])]  # 索引与布尔的结合

array([[3, 5],
       [6, 8]])

当数组维度为1时，可以直接进行布尔索引，而无需np.ix_

In [80]:
new = target.reshape(-1)
new

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [81]:
new[new%2==0]

array([0, 2, 4, 6, 8])

In [82]:
new%2   # % 取余 

array([0, 1, 0, 1, 0, 1, 0, 1, 0])

## 4.常用函数

#### 【a】where 

In [85]:
a = np.array([-1,1,-1,0])
np.where(a>0)

(array([1]),)

In [86]:
a = np.array([-1,1,-1,0])
np.where(a>0,a,5)   # a和5 需共同给出

array([5, 1, 5, 5])

In [88]:
a

array([-1,  1, -1,  0])

In [89]:
np.where(a)  # 返回非0元素的索引（下标）

(array([0, 1, 2]),)

In [92]:
b = np.array([[1,0,3],
             [4,5,0]])
np.where(b)     #结果对应关系 (0，0),(0,2),(1,0),(1,1)

(array([0, 0, 1, 1]), array([0, 2, 0, 1]))

#### 【b】 nonzero,argmax,argmin

In [93]:
a = np.array([-2,-5,0,1,3,-1])
np.nonzero(a)

(array([0, 1, 3, 4, 5]),)

In [94]:
np.where(a)

(array([0, 1, 3, 4, 5]),)

In [95]:
np.argmax(a)

4

In [96]:
np.argmin(a)

1

#### 【c】any，all

In [97]:
a = np.array([0,1])
a.any()

True

In [98]:
a.all()

False

#### 【d】cumprod,cumsum,diff